apiVersion: apps/v1
kind: Deployment
metadata:
  name: proman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proman
  template:
    metadata:
      labels:
        app: proman
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: proman
          image: ghcr.io/jigle/proman:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_ENV
              value: "production"
            - name: HOSTNAME
              value: "0.0.0.0"
            - name: PORT
              value: "3000"
            - name: NEXTAUTH_URL
              value: "https://your.domain"
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: proman-secrets
                  key: NEXTAUTH_SECRET
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: proman-secrets
                  key: DATABASE_URL
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: proman-secrets
                  key: SENDGRID_API_KEY
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: proman-data
              mountPath: /data
      volumes:
        - name: proman-data
          persistentVolumeClaim:
            claimName: proman-data
