apiVersion: v2
name: proman
description: A Helm chart for deploying the Proman property management platform
type: application
version: 1.1.0
appVersion: "1.1.0"
home: https://github.com/JIGLE/proman
sources:
  - https://github.com/JIGLE/proman
  - https://ghcr.io/jigle/proman
keywords:
  - property
  - management
  - nextjs
  - sqlite
maintainers:
  - name: Proman Maintainers
    url: https://github.com/JIGLE
icon: https://raw.githubusercontent.com/JIGLE/proman/main/public/proman-icon.svg