apiVersion: v2
name: proman
description: Proman Next.js application
type: application
version: 0.2.1
appVersion: "latest"
icon: https://raw.githubusercontent.com/JIGLE/Proman/main/public/icon.png
keywords:
  - truenas
  - proman
  - nextjs
maintainers:
  - name: JIGLE
    email: support@example.com
