rules:
  - match:
      dependency_type: "development"
      update_type: "patch"
  - match:
      dependency_type: "production"
      update_type: "patch"
  - match:
      dependency_name: "actions/*"
      update_type: "patch"
  - match:
      dependency_name: "docker/*"
      update_type: "patch"
  - match:
      dependency_name: "@types/*"
      update_type: "patch"
  - match:
      dependency_name: "eslint*"
      update_type: "patch"
  - match:
      dependency_name: "vitest*"
      update_type: "patch"
  - match:
      dependency_name: "@testing-library/*"
      update_type: "patch"
  - match:
      dependency_name: "typescript"
      update_type: "patch"
  - match:
      dependency_name: "prettier"
      update_type: "patch"