{{- if .Values.persistence.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "proman.fullname" . }}-prisma-init
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-delete-policy": "hook-succeeded"
  labels:
    {{- include "proman.labels" . | nindent 4 }}
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        {{- include "proman.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ include "proman.serviceAccountName" . }}
      containers:
        - name: prisma-init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "sh", "-c", "npx prisma db push --schema=prisma/schema.prisma && npx prisma generate" ]
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.mountPath | default "/app/data" | quote }}
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "proman.fullname" . }}-pvc
      {{- end }}
{{- end }}